import json
import urllib.request
import urllib.parse
import os

QUESTIONS = [
    "What is the annual leave entitlement?",
    "How far in advance should leave be requested?",
    "What is the remote work policy?",
    "What are the password requirements?",
    "What are the main requirements for working remotely?",
    "How do the leave and remote work policies relate to each other?",
    "What are the main employee responsibilities described in the policies?",
    "What was the company's revenue last year?",
    "Who is the company's CEO?",
    "What is the company's stock price today?"
]

def query_agent(question):
    url = "http://localhost:5000/api/research"
    data = json.dumps({"query": question}).encode("utf-8")
    req = urllib.request.Request(
        url, 
        data=data, 
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    try:
        with urllib.request.urlopen(req) as res:
            return json.loads(res.read().decode("utf-8"))
    except Exception as e:
        print(f"Error querying question '{question}': {e}")
        return None

def main():
    print("Generating real cited answers...")
    markdown_content = (
        "# Cited Answers — CEREBRO Research Agent\n\n"
        "*Generated by querying the actual running agent on standard policy documents. "
        "Running in local fallback mode (no OPENAI_API_KEY configured).* \n\n"
    )
    
    for idx, q in enumerate(QUESTIONS, start=1):
        print(f"Processing question {idx}/10: {q}")
        res = query_agent(q)
        if not res:
            continue
        
        markdown_content += f"## Question {idx}: {q}\n\n"
        markdown_content += f"**Answer:**\n\n{res.get('answer')}\n\n"
        markdown_content += f"**Grounded:** {not res.get('insufficient_evidence')}\n\n"
        markdown_content += f"**Relevance Score:** {res.get('retrieval_info', {}).get('top_score', 0.0)}\n\n"
        
        citations = res.get("citations", [])
        if citations:
            markdown_content += "### Sources Cited:\n\n"
            for c in citations:
                markdown_content += f"- **[{c['id']}] {c['source']}** — Section: {c.get('section', 'General')} (Relevance: {c.get('relevance', 'Low')} - {c.get('score')})\n"
            markdown_content += "\n### Supporting Passages:\n\n"
            for c in citations:
                markdown_content += f"#### [{c['id']}] Excerpt:\n> {c.get('passage')}\n\n"
        
        markdown_content += "---\n\n"
        
    out_path = os.path.join(os.path.dirname(__file__), "cited_answers.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)
    print(f"Saved real outputs to {out_path}")

if __name__ == "__main__":
    main()
